### ISSUE TITLE
Update for media_player.philips_tv fails

### ISSUE THREAD

**Issue by oktayoner** [mveken/home_assistant#1]
Component works like a charm.
But in my Home Assistant error log it is full with "Update for media_player.philips_tv fails"

`
Update for media_player.philips_tv fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 327, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 308, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/media_player/philips_2016.py", line 161, in update
    self._tv.update()
  File "/home/homeassistant/.homeassistant/custom_components/media_player/philips_2016.py", line 229, in update
    self.getChannel()
  File "/home/homeassistant/.homeassistant/custom_components/media_player/philips_2016.py", line 234, in getChannel
    self.channel_id = r["channel"]["preset"]
KeyError: 'preset'
`
And the status doesn't appear correctly, for instance, the TV is now on and watching Netflix.

![philips](https://user-images.githubusercontent.com/5961479/36933996-b4846904-1ee2-11e8-8a60-44f10c3bb91c.jpg)

I'm not familiar with Python, but it looks like the TV doesn't reply, the weird part is that it does react to the commands (Volume Up/Down, Mute, Pause, Next, Back)
The TV is an 55PUS6272/12

**Comment by mveken** [comment]
Hi,

The component tries to update itself every 15 seconds. One of the things that gets updated is the current channel information (preset and name). It appears that on your tv there is no preset information of the channel available, hence the error you see. The description of the API of the television is very limited. I figured a lot of stuff out by looking at the responses that I get from my set. I've tested this using Python because you need to re-use the HTTPS connection, because otherwise the set will hang after exactly 100 requests. I think it has some kind of session cache that is limited to 100 sessions that effectively DOS-es the system at request 101. But you can test it in the browser if you do not have a lot of programming experience. If you browse to:
`https://<<your IP goes here>>:1926/6/activities/tv` you'll be asked to trust the SSL certificate and for a set of credentials. You can use the username/password that you got in the pairing process. The response I get looks like this:
`{"channel":{"ccid":352,"preset":"4","name":"RTL 4 HD"},"channelList":{"id":"allcab","version":"58"}}`
You can see that the channel dictionary contains both a "preset" and a "name" item.
Look at the response you get and post it here. Then I'll try to adapt the code so it will support your set too.

By the way: I've not been able to figure out how to retrieve info on the "source" being watched. So if you watch Netflix you will still see the TV channel that is selected. I will try to fix that, but it will take some research.

**Comment by oktayoner** [comment]
The weird part is that my TV doesn't accept the HTTPS connection, but does everything over HTTP, and port 1925 instead of 1926. I have not been able to retrieve any username or password, but it still accepts commands from HA. 

I do not watch TV directly from TV but via a decoder (iTV), so my channellist is empty. (My ISP doesn't have a CI+ card for digital TV and doesnt support iTV directly to a source exept the decoder).

When I get home I will check if 6/activities/tv gives any response for Netflix (I doubt).

If I can do anything, just let me know.
